Fix missing devicePixelRatio() ui stub cmd for rvio (#872)
### Fix missing devicePixelRatio() ui stub cmd in rvio

### Linked issues
NA

### Summarize your change.
rvio has its own set of stub UI commands which are effectively noop to
make sure it can loads other scripts with UI command. The
devicePixelRatio() UI command was recently introduced but I omitted to
add an associated stub command to rvio. My bad.

### Describe the reason for the change.

rvio was complaining about the missing devicePixelRatio() command:
RV.app/Contents/PlugIns/Mu/rvtypes.mu, line 530, char 49: Unresolved
function call to "devicePixelRatio"
ERROR: while loading source module
"/RV.app/Contents/PlugIns/Mu/rvtypes.mu"
ERROR: attempted call to unresolved function
RV.app/Contents/PlugIns/Mu/glyph.mu, line 527, char 43: Unresolved
function call to "devicePixelRatio"
ERROR: while loading source module
"RV.app/Contents/PlugIns/Mu/[glyph.mu](http://glyph.mu/)"

### Describe what you have tested and on which operating system.
Successfully tested on macOS

### Add a list of changes, and note any that might need special
attention during the review.

### If possible, provide screenshots.

Signed-off-by: Bernard Laberge <bernard.laberge@autodesk.com>