Prevent 2x Qt broken components from being installed (#371)
### Prevent 2x Qt broken components from being installed

### Linked issues
NA

### Describe the reason for the change.
2x Qt frameworks were causing Apple codesign to fail with the following
error: "unsealed contents present in the bundle root" :
- QtRepParser
- QtUiPlugin

This commit fixes the Apple codesign issue for these 2 frameworks.

### Summarize your change.
Prevent the 2 following Qt frameworks from being installed because they
are broken (they don't have any binary associated with them):
- QtRepParser
- QtUiPlugin

### Describe what you have tested and on which operating system.
Sucesfully tested on Mac

### Add a list of changes, and note any that might need special
attention during the review.

### If possible, provide screenshots.

Signed-off-by: Bernard Laberge <bernard.laberge@autodesk.com>