fix: Revert fix: Fix crashes when calling sourcesAtFrame when clearing (#1185)
### Revert fix: Fix crashes when calling sourcesAtFrame when clearing

### Linked issues
NA

### Summarize your change.

Reverted this commit to fix regression:

https://github.com/AcademySoftwareFoundation/OpenRV/commit/02a537b494ba4862f92750a6cea3a69fcb4f10c8

### Describe the reason for the change.

The commit that is being reverted in this commit caused a regression.
The following errors when clearing an RV session:
```
ERROR: event = before-graph-view-change
ERROR: function = __lambdac96 (void; Event event)
ERROR: Exception Value: exception: "nil argument to function"
ERROR: event = after-graph-view-change
ERROR: function = __lambdadd8 (void; Event event)
ERROR: Exception Value: exception: "nil argument to function"
ERROR: event = graph-node-inputs-changed
ERROR: function = __lambdadd9 (void; Event event)
ERROR: Exception Value: exception: "nil argument to function"
Traceback (most recent call last):
 File "/private/var/folders/10/sd1gk1s527bfkdmmlbg7352c0000gn/T/AppTranslocation/919C640B-34AC-4B5F-A9AE-D30F60636CDB/d/RV.app/Contents/PlugIns/Python/source_setup.py", line 505, in checkForDisplayGroup
   if commands.nodeType(event.contents()) == "RVDisplayGroup":
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: Exception thrown while calling commands.nodeType -- exception: "nil argument to function"
Traceback (most recent call last):
 File "/private/var/folders/10/sd1gk1s527bfkdmmlbg7352c0000gn/T/AppTranslocation/919C640B-34AC-4B5F-A9AE-D30F60636CDB/d/RV.app/Contents/PlugIns/Python/source_setup.py", line 505, in checkForDisplayGroup
   if commands.nodeType(event.contents()) == "RVDisplayGroup":
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: Exception thrown while calling commands.nodeType -- exception: "nil argument to function"
```

### Describe what you have tested and on which operating system.
Successfully tested on macOS

### Add a list of changes, and note any that might need special
attention during the review.

### If possible, provide screenshots.

Signed-off-by: Bernard Laberge <bernard.laberge@autodesk.com>
Signed-off-by: Dean Macri <dean.p.macri@gmail.com>