Fix path swap variable when broadcasting addSource*** commands. (#888)
### Summarize your change.

Fixed path swap environment variable not working anymore.

When using RemoteRvCommands, the path swap variable was stripped out and
replaced before broadcasting the path values. This fix prevents this
from happening.

### Describe the reason for the change.
bug reported by customer

### Describe what you have tested and on which operating system.
Successfully tested on macOS connected to a Windows machine in an
RV<->RV Live Review Session.

**Steps to Reproduce:**
Note that you need two machines with the same media at different
location to reproduce this issue.

- Dowload a sample media to both machines.
- On each machine, set the RV_PATHSWAP_MYSHOW environment variable
pointing to the folder where the media is located making sure to use
different location
-  Example RV#1: export RV_PATHSWAP_MYSHOW="/Users/labergb/media"
-  Example RV#2: export RV_PATHSWAP_MYSHOW="/c/media"
- Launch RV#1 and Create a Live Review Session
- Launch RV#2 and Join this Live Review Session
- In RV#1, Open the Python console: RV/Tools/Python Console menu
- In RV#2, Execute the following python script from the Python console:
- from rv import commands as rvc
- rvc.addSourceVerbose(["/Users/labergb/media/mr_robot_vibe.mov"])

Expected: the media should load fine on RV#2
What you get: The following error is reported in RV#2:
ERROR: Open of '/Users/labergb/media/mr_robot_vibe.mov' failed: No such
file or directory

The same error occurs for addSources() and addSourcesVerbose()
You can use the following python code snippet to reproduce it:

from rv import commands as rvc
rvc.addSources(["[", "/Users/labergb/media/mr_robot_vibe.mov", "]"])
from rv import commands as rvc
rvc.addSourcesVerbose([["/Users/labergb/media/mr_robot_vibe.mov"]])

### Add a list of changes, and note any that might need special
attention during the review.
trivial fixes

### If possible, provide screenshots.

Signed-off-by: Patrick Bergeron <patrick.bergeron@autodesk.com>
Co-authored-by: Bernard Laberge <117092886+bernie-laberge@users.noreply.github.com>
Signed-off-by: Sam.Richards@taurich.org <Sam.Richards@taurich.org>