add utf-8 compile flag for spdlog and oiio that lean on fmt
Windows builds failing on spdlog and oiio because they bundle fmt which requires a utf-8 flag when compiling  on windows.

Error was D:\a\OpenRV\OpenRV\_build\RV_DEPS_SPDLOG\install\include\spdlog\fmt\bundled\base.h(465,28): error C2338: static_assert failed: 'Unicode support requires compiling with /utf-8' [D:\a\OpenRV\OpenRV\_build\src\lib\base\TwkUtil\TwkUtil.vcxproj]

Signed-off-by: Michael Oliver <mcoliver@gmail.com>