Fix ERROR: while loading source module inspector.mu (#1001)
### Fix ERROR: while loading source module inspector.mu

### Linked issues
NA

### Describe the reason for the change.
When activating the Color Inspector, its menu failed to initialize
properly and the following error was reported:
```
ERROR: while loading source module "../Mu/inspector.mu"
ERROR: syntax error
```

This is a recent regression

### Summarize your change.
Removed the trailing comma at the end of the color inspector's menu
definition which was the source of the error
(At the end of "Close Inspector")

Also in this commit: Fixed the eventPattern, category inversion for the
8bits/10bits/12bits/16bits menu items.

Thanks to @markreidvfx for reporting it !

### Describe what you have tested and on which operating system.
Successfully tested on macOS

### Add a list of changes, and note any that might need special
attention during the review.

### If possible, provide screenshots.

Signed-off-by: Bernard Laberge <bernard.laberge@autodesk.com>