Fix rvio media_library_event_plugin related error (#398)
### Fix rvio media_library_event_plugin related error

### Linked issues
NA

### Summarize your change.
Make the media_library_demo.media_library_event_plugin load without
error when run from rvio (which does not support modes)

### Describe the reason for the change.
rvio was reporting the following non fatal error:
```
Failed to load media_library_demo.media_library_event_plugin
...
ModuleNotFoundError: No module named 'rv.commands'
```

### Describe what you have tested and on which operating system.
Successfully built and tested on Mac. 
This fix is not OS specific.

### Add a list of changes, and note any that might need special
attention during the review.

### If possible, provide screenshots.

Signed-off-by: Bernard Laberge <bernard.laberge@autodesk.com>