Fix syntax error in rvtypes (#1052)
### Fix rvtypes syntax error

### Summarize your change.

When using a tool that uses rvtypes, like rvio you can see a syntax
error in the shell. For example:
```
./rvio -v -err-to-out /dev/null -o /tmp/t.mov -leader simpleslate test
```
An error like this appears in the output:
```
ERROR: while loading source module "/Users/nelsonr/git/rv/_build_debug/stage/app/RV.app/Contents/PlugIns/Mu/rvtypes.mu"
ERROR: syntax error
```

It turns out the cause of this the variable named glyph. There is also a
module named glyph which shadows the variable, and hence when the code
references the variable it resolves to the module and generates a syntax
error.


### Describe the reason for the change.

In the context of rvio this never really caused a problem since the
glyph variable is only used in the UI, but it's worth fixing anyway
since it could cause potential problems in the UI and seeing that output
in rvio makes users question whether it actually worked or not.

### Describe what you have tested and on which operating system.

Mac OS Tahoe 26.1

Signed-off-by: Roger Nelson <roger.nelson@autodesk.com>