Fix build when using latest Xcode 16.3-clang 17 (#772)
### Fix build when using latest Xcode 16.3-clang 17

### Linked issues
NA

### Describe the reason for the change.

The Open RV build got broken with the latest macOS Sequoia 15.5 + Xcode
16.3-clang17 + latest Homebrew.
This commit fixes these errors and also update the Open RV build
instructions on macOS.

Note that this commit is not enough to successfully build Open RV with
the latest macOS.
It is missing one template error which has been fixed in a separate repo
and will be added to this PR once it is merged merged:
https://github.com/shotgunsoftware/openrv-pub/pull/21

### Summarize your change.

This commit fixes numerous legacy template errors that were not reported
as such by previous versions of clang.
This commit also contains some changes in the Open RV build instructions
on macOS in order to achieve a successful Open RV build on the latest
macOS configuration.

- Updated PNG from 16.39.0 to 16.48.0 to fix the following issue:
```
In file included from /Users/labergb/openrv_bernie/OpenRV/_build/RV_DEPS_PNG/src/scripts/intprefix.c:21:
/Users/labergb/openrv_bernie/OpenRV/_build/RV_DEPS_PNG/src/scripts/../pngpriv.h:524:16: fatal error: 'fp.h' file not found
  524 | #      include <fp.h>
```
We need this fix:

https://github.com/pnggroup/libpng/commit/893b8113f04d408cc6177c6de19c9889a48faa24
Which is in 1.6.48

- Updated zlib from 1.2.13 to 1.3.1 to fix the following issue:
```
In file included from /Users/labergb/openrv_bernie/OpenRV/_build/RV_DEPS_ZLIB/src/zutil.c:10:
In file included from /Users/labergb/openrv_bernie/OpenRV/_build/RV_DEPS_ZLIB/src/gzguts.h:21:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/stdio.h:61:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/_stdio.h:318:7: error: expected identifier or '('
  318 | FILE    *fdopen(int, const char *) __DARWIN_ALIAS_STARTING(__MAC_10_6, __IPHONE_2_0, __DARWIN_ALIAS(fdopen));
      |          ^
/Users/labergb/openrv_bernie/OpenRV/_build/RV_DEPS_ZLIB/src/zutil.h:147:33: note: expanded from macro 'fdopen'
  147 | #        define fdopen(fd,mode) NULL /* No fdopen() */
      |                                 ^
/Applications/Xcode.app/Contents/DeIn file included from /Users/labergb/openrv_bernie/OpenRV/_build/RV_DEPS_ZLIB/src/zutil.c:10:
```

We need this commit available in ZLIB 1.3.1:

https://github.com/madler/zlib/commit/4bd9a71f3539b5ce47f0c67ab5e01f3196dc8ef9

Fix: Use char16_t instead of unsigned short to fix the following error:
```
In file included from /Users/labergb/openrv_bernie/OpenRV/src/lib/mu/Mu/UTF8.cpp:10:
In file included from /Users/labergb/openrv_bernie/OpenRV/src/lib/mu/Mu/Mu/UTF8.h:10:
In file included from /Users/labergb/openrv_bernie/OpenRV/src/lib/mu/Mu/Mu/config.h:9:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/c++/v1/string:821:42: error: implicit instantiation of undefined template 'std::char_traits<unsigned short>'
  821 |   static_assert(is_same<_CharT, typename traits_type::char_type>::value,
      |                                          ^
/Users/labergb/openrv_bernie/OpenRV/src/lib/mu/Mu/UTF8.cpp:62:17: note: in instantiation of template class 'std::basic_string<unsigned short, std::char_traits<unsigned short>, gc_allocator<unsigned short>>' requested here
   62 |     UTF16String UTF16convert(const Mu::String& s)
      |                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.4.sdk/usr/include/c++/v1/__string/char_traits.h:45:8: note: template is declared here
   45 | struct char_traits;
      |        ^
In file included from /Users/labergb/openrv_bernie/OpenRV/src/lib/mu/Mu/UTF8.cpp:10:
```

### Describe what you have tested and on which operating system.
Successfully tested both on macOS 15.4.1 and macOS 15.5 which was
released today.
XCode 16.3 and Qt 6.5.3 were used.

### Add a list of changes, and note any that might need special
attention during the review.

### If possible, provide screenshots.

Signed-off-by: Bernard Laberge <bernard.laberge@autodesk.com>
Signed-off-by: Sam.Richards@taurich.org <Sam.Richards@taurich.org>